spring:
  main:
    banner-mode: OFF

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://docker:3306/c05607477
    username: root
    password: qwer1234

logging:
  level:
    org.springframework.web: DEBUG
