-- MySQL Script generated by MySQL Workbench
-- Sat Dec 31 01:15:35 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `pin_code` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `account` ;

CREATE TABLE IF NOT EXISTS `account` (
  `account_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `account_no` VARCHAR(255) NULL DEFAULT NULL,
  `account_type` VARCHAR(10) NULL DEFAULT NULL,
  `balance` BIGINT(20) NOT NULL DEFAULT '0',
  `credit_card` VARCHAR(255) NULL DEFAULT NULL,
  `sort_code` INT(11) NULL DEFAULT NULL,
  `transaction_list` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`account_id`),
  INDEX `account_user_id_fk` (`user_id` ASC),
  CONSTRAINT `account_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transaction` ;

CREATE TABLE IF NOT EXISTS `transaction` (
  `tx_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tx_no` VARCHAR(100) NOT NULL DEFAULT '',
  `source_account_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `target_account_id` INT(11) UNSIGNED NOT NULL,
  `amount` BIGINT(20) UNSIGNED NOT NULL,
  `before_balance` BIGINT(20) UNSIGNED NOT NULL,
  `after_balance` BIGINT(20) UNSIGNED NOT NULL,
  `tx_type` VARCHAR(20) NOT NULL,
  `tx_status` VARCHAR(20) NOT NULL DEFAULT '',
  `reason` VARCHAR(255) NULL DEFAULT '',
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`tx_id`),
  INDEX `tx_from_account_id_fk` (`source_account_id` ASC),
  INDEX `tx_to_account_id_fk` (`target_account_id` ASC),
  CONSTRAINT `tx_source_account_id_fk`
    FOREIGN KEY (`source_account_id`)
    REFERENCES `account` (`account_id`),
  CONSTRAINT `tx_target_account_id_fk`
    FOREIGN KEY (`target_account_id`)
    REFERENCES `account` (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
