-- MySQL Script generated by MySQL Workbench
-- Fri Dec 30 15:11:12 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema c05607477
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema c05607477
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `c05607477` DEFAULT CHARACTER SET latin1 ;
USE `c05607477` ;

-- -----------------------------------------------------
-- Table `c05607477`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c05607477`.`user` ;

CREATE TABLE IF NOT EXISTS `c05607477`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `pin_code` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `c05607477`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c05607477`.`account` ;

CREATE TABLE IF NOT EXISTS `c05607477`.`account` (
  `account_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `account_no` VARCHAR(255) NULL DEFAULT NULL,
  `account_type` VARCHAR(10) NULL DEFAULT NULL,
  `balance` BIGINT(20) NOT NULL DEFAULT '0',
  `credit_card` VARCHAR(255) NULL DEFAULT NULL,
  `sort_code` INT(11) NULL DEFAULT NULL,
  `transaction_list` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`account_id`),
  INDEX `account_user_id_fk` (`user_id` ASC),
  CONSTRAINT `account_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `c05607477`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
